export THIRDPARTY_PATH=/Users/cateye/release/3rdParty
/Applications/CMake.app/Contents/bin/cmake ./ -G Xcode -DOSGEARTH_BUILD_PLATFORM_IPHONE:BOOL=ON \
-DIPHONE_SDKVER="10.3" \
-DIPHONE_VERSION_MIN="8.0" \
-DOSG_DIR:PATH="/Users/cateye/projects/osg-ios/osg-es" \
-DCURL_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/curl-ios-device/include" \
-DCURL_LIBRARY:PATH="$THIRDPARTY_PATH/curl-ios-device/lib/libcurl.a" \
-DGDAL_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/gdal-ios-device/include" \
-DGDAL_LIBRARY:PATH="$THIRDPARTY_PATH/gdal-ios-device/lib/libgdal.a" \
-DGEOS_INCLUDE_DIR:PATH="$THIRDPARTY_PATH/geos-ios-device/include/source/headers" \
-DGEOS_LIBRARY:PATH="$THIRDPARTY_PATH/geos-ios-device/lib/libGEOS_3.2.a" \
-DOSGEARTH_BUILD_APPLICATION_BUNDLES:BOOL=OFF \
-DDYNAMIC_OSGEARTH:BOOL=OFF \
-DOSGEARTH_USE_QT:BOOL=OFF
